name: CI-Android

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 1 * *' # Run at 1AM every first day in month
  workflow_dispatch:

env:
  BUILD_DIR: ${{ github.workspace }}/_build

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '17'

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.28.1'

    - name: Check version
      run: cmake --version

    - name: Configure CMake
      run: |
        mkdir "${{ env.BUILD_DIR }}"
        cd "${{ env.BUILD_DIR }}"
        cmake -D CMAKE_BUILD_SYSTEM=Android ..
      shell: cmd

    - name: Build
      working-directory: ${{ env.BUILD_DIR }}
      run: |
        gradlew build
      shell: cmd

    - name: Pack
      working-directory: ${{env.BUILD_DIR}}
      run: |
        cpack
      shell: cmd

    - name: Store artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{github.event.repository.name}}
        path: ${{github.workspace}}/*.zip
        retention-days: 5
