name: CI-Windows-Ninja-Clang

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 1 * *' # Run at 1AM every first day in month
  workflow_dispatch:

env:
  BUILD_DIR: ${{ github.workspace }}/_build

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        tags: true

    - name: Check version
      run: cmake --version

    - name: Configure CMake
      run: |
        cmake -B "${{ env.BUILD_DIR }}" . ^
          -G "Ninja" ^
          -D CMAKE_C_COMPILER=clang ^
          -D CMAKE_CXX_COMPILER=clang++ ^
          -D CMAKE_CXX_STANDARD=23 ^
          -D CMAKE_CXX_STANDARD_REQUIRED=ON
      shell: cmd

    - name: Build
      working-directory: ${{env.BUILD_DIR}}
      run: |
        cmake --build .
      shell: cmd

    - name: Test
      working-directory: ${{env.BUILD_DIR}}
      run: |
        ctest --output-on-failure
      shell: cmd

