name: Release-Window

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

env:
  BUILD_DIR: ${{ github.workspace }}/_build

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        tags: true

    - name: Check version
      run: cmake --version

    - name: Configure CMake
      run: |
        cmake --preset msvc -D USE_NSIS=ON
      shell: cmd

    - name: Build
      run: |
        cmake --build --preset build-msvc-release
      shell: cmd

    - name: Pack
      working-directory: ${{env.BUILD_DIR}}
      run: |
        cpack
      shell: cmd

    - name: Store artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Release-Build
        path: ${{env.BUILD_DIR}}/*.exe
        retention-days: 5
