name: Release-Android

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '17'

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.28.1'

    - name: Check version
      run: cmake --version

    - name: Configure CMake
      run: |
        mkdir "${{ env.BUILD_DIR }}"
        cd "${{ env.BUILD_DIR }}"
        cmake -D BUILD_ANDROID=ON ..
      shell: cmd

    - name: Build
      working-directory: ${{ github.workspace }}/bin-android
      run: |
        gradlew build
      shell: cmd
    
    - name: Store artifact
      run: |
        echo Not yet implemented
        exit 1
      shell: cmd
