name: Release-Android

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

env:
  BUILD_DIR: ${{ github.workspace }}/_build
  KEYSTORE_PATH: ${{ github.workspace }}/android-release-key.jks

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '17'

    
    - name: Set up keystore
      run: |
        $bytes = "${{ secrets.APK_KEYSTORE_BASE64 }}"
        [System.IO.File]::WriteAllBytes("${{ env.KEYSTORE_PATH }}", [Convert]::FromBase64String($bytes))
      shell: powershell

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.28.1'

    - name: Check version
      run: cmake --version

    - name: Configure CMake
      run: |
        mkdir "${{ env.BUILD_DIR }}"
        cd "${{ env.BUILD_DIR }}"
        cmake -D CMAKE_BUILD_SYSTEM=Android ..
      shell: cmd
      env:
        APK_KEYSTORE_PATH: ${{ env.KEYSTORE_PATH }}
        APK_KEYSTORE_PASSWORD: ${{ secrets.APK_KEYSTORE_PASSWORD }}
        APK_SIGNING_KEY_ALIAS: ${{ secrets.APK_KEY_ALIAS }}
        APK_SIGNING_KEY_PASSWORD: ${{ secrets.APK_KEYSTORE_PASSWORD }}

    - name: Build
      working-directory: ${{ env.BUILD_DIR }}
      run: |
        gradlew build
      shell: cmd

    - name: Pack
      working-directory: ${{env.BUILD_DIR}}
      run: |
        cpack -C Release
      shell: cmd

    - name: Store artifact
      uses: actions/upload-artifact@v4
      with:
        name: Android-Release-Build
        path: ${{env.BUILD_DIR}}/*.zip
        retention-days: 5
