name: Static-Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BUILD_DIR: ${{github.workspace}}/vsbuild

jobs:
  build:
    runs-on: windows-2025

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        tags: true

    - name: Check version
      run: cmake --version

    - name: Configure CMake
      run: |
        cmake --preset msvc -D ENABLE_LINTER=ON
      shell: cmd

    - name: Build
      run: |
        cmake --build --preset build-msvc-debug
      shell: cmd

