name: Static-Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BUILD_DIR: ${{github.workspace}}/vsbuild

jobs:
  build:
    runs-on: windows-2025

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        tags: true

    - name: Check version
      run: cmake --version

    - name: Configure CMake
      run: |
        cmake -B "${{ env.BUILD_DIR }}" . ^
          -D CMAKE_CXX_STANDARD=23 ^
          -D CMAKE_CXX_STANDARD_REQUIRED=ON ^
          -D CMAKE_GENERATOR_PLATFORM=x64 ^
          -D ENABLE_LINTER=ON
      shell: cmd

    - name: Build
      working-directory: ${{env.BUILD_DIR}}
      run: |
        cmake --build . --config Debug
      shell: cmd

