name: Static-Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BUILD_DIR: ${{github.workspace}}/vsbuild

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        tags: true

    - name: Check version
      run: cmake --version

    - name: Configure CMake
      run: |
        mkdir "${{ env.BUILD_DIR }}"
        cd "${{ env.BUILD_DIR }}"
        cmake -D ENABLE_LINTER=ON ..
      shell: cmd

    - name: Build
      working-directory: ${{env.BUILD_DIR}}
      run: |
        cmake --build . --config Debug
      shell: cmd

    - name: Install cppcheck
      run: |
        winget install -e --id Cppcheck.Cppcheck
      shell: cmd

    - name: Cppcheck
      working-directory: ${{github.workspace}}
      run: |
        cppcheck ./lib/src/ \
        -I ./lib/include/ \
        -I _build/_deps/dgm-engine-core-lib-src/lib/include/ \
        -I ./lib/private_include/ \
        --enable=all \
        --suppress=unusedFunction \
        --suppress=missingIncludeSystem \
        --suppress=incorrectStringBooleanError
      shell: cmd
